import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect, useCallback } from 'react';
import { useStore, useDispatch, connect } from 'react-redux';
import styled from 'styled-components';
import { faUserTie } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import _ from 'lodash';

import {
  getMinutesGapFromMillionseconds,
  getHumanReadableTimerBySecond,
  fetchAPI,
  isBrowserMode,
  showModal,
  ACTIVE,
  FRAME_GAP,
  INVALID_TIME_VALUE,
} from '../lib';
import {
  getLogger
} from '../lib/logger';
import {
  SET_TIME,
  UNSET_TIME,
  CHECK_TERMINATE,
} from '../lib/actions';
import {
  Wrapper,
  Layout,
  SectionTitle,
  SectionContainer,
  Button,
  HorizontalStretch,
  Input,
} from '../components';
import {
  HurrayModal,
} from '../components/HurrayModal';
import {
  AlertModal,
} from '../components/AlertModal';

import styles from '../styles/Home.module.css'

const logger = getLogger();

const TimerWrapper = styled.div`
  display: flex;
  justify-content: center;
  flex: 1;

  &.timer {
    color: #313fde;
    align-items: center;
    font-size: 75px;
    font-size: 15vh; // compatible style
  }
`;

const UserItem = styled.div`
  margin-bottom: 30px;

  & .icon {
    margin-right: 20px;
  }
`;

const LotteryPage = ({ time: initTime, users, modalStatus }) => {
  const store = useStore();
  const now = Date.now();
  const [time, setTime] = useState(getMinutesGapFromMillionseconds(initTime));
  const [currentTimestamp, setCurrentTimestamp] = useState(now);
  const dispatch = useDispatch();
  useEffect(() => {
    const iterator = {
      done: false,
      async next() {
        const done = this?.done;
        const now = Date.now();
        !done && setCurrentTimestamp(now);
        dispatch({ type: CHECK_TERMINATE });
        await new Promise(res => setTimeout(res, FRAME_GAP));
        return {
          done,
          value: now,
        }
      },
      [Symbol.asyncIterator]() {
        return this;
      }
    }
    const startTimer = async () => {
      for await(let item of iterator) {}
    };
    startTimer();
    return () => {
      // NOTE: make iterator done
      iterator.done = true;
    };
  }, []);

  const onSetTimeBtnClicked = useCallback(async ({ value }) => {
    const time = _.chain(value).parseInt().ceil(0).value();
    if (!_.chain(time).clamp(0, 1440).isEqual(time).value()) {
      await showModal({ component: AlertModal, props: { message: INVALID_TIME_VALUE } });
      return;
    }
    dispatch({ type: SET_TIME, payload: { value: time } });
  });

  useEffect(() => {
    logger.DEBUG('initTime', initTime);
    if (initTime === null && modalStatus === ACTIVE) {
      dispatch({ type: UNSET_TIME });
      const user = _.chain(users).sample().value();
      showModal({ component: HurrayModal, props: { user } });
    }
  }, [
    initTime,
    modalStatus,
  ]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Treasure picker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Wrapper className="main">
          <SectionTitle className="align-left">抽獎時間</SectionTitle>
          <SectionContainer>
            <Wrapper className="content">
              <Input
                max="1440"
                min="0"
                type="number"
                value={_.chain(time).ceil(0).value()}
                onInput={({ target }) => setTime(target?.value)}
              />
              <HorizontalStretch />
              分鐘
              <HorizontalStretch size={30} />
              <Button onClick={() => onSetTimeBtnClicked({ value: time })}>
                設定
              </Button>
            </Wrapper>
            <TimerWrapper className="timer">
              { getHumanReadableTimerBySecond({ value: initTime - now, formatter: value => value / 1000 }) }
            </TimerWrapper>
          </SectionContainer>
        </Wrapper>
        <Wrapper className="left-side">
          <SectionTitle>參加抽獎名單</SectionTitle>
          <SectionContainer>
            {
              users.map(item => {
                return (
                  <UserItem key={item?.id} style={{ color: item?.color }}>
                    <FontAwesomeIcon icon={faUserTie} size="6x" className="icon" />
                    { item?.userName }
                  </UserItem>
                );
              })
            }
          </SectionContainer>
        </Wrapper>
      </Layout>
    </div>
  )
}

LotteryPage.getInitialProps = async ({ req }) => {
  const apiHost = _.chain(req)
    .get('headers.host')
    .value();
  const protcol = _.chain(req)
    .get('httpVersion')
    .isEqual('1.1')
    .thru(value => value ? 'http' : 'https')
    .value();
  const apiEndpoint = isBrowserMode ? '/api/people' : `${protcol}://${apiHost}/api/people`;
  const res = await fetchAPI(apiEndpoint);
  const json = await res.json();
  return { users: json };
};

// NOTE: https://github.com/kirill-konshin/next-redux-wrapper#getserversideprops
export default connect(state => ({
  time: state?.timer?.value,
  modalStatus: state?.timer?.modalStatus,
}))(LotteryPage);
